version: '3.7'

services:
    redis:
        image: redis:alpine
        command:
          - redis-server
        env_file:
          - ./.env
        restart: on-failure
        ports:
          - "6378:6378"
    postgres_db:
        image: postgres:14.5-alpine
        restart: on-failure
        env_file:
            - ./.env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"

volumes:
    postgres_data: