"""init
Revision ID: 257717936dc6
Revises:
Create Date: 2023-05-21 12:53:43.425867
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '257717936dc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subs_table = op.create_table(
        'subscriptions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('payment_name', sa.VARCHAR(length=32), nullable=False),
        sa.Column('humanize_name', sa.VARCHAR(length=32), nullable=False),
        sa.Column('payment_amount', sa.Integer(), nullable=False),
        sa.Column('payment_currency', sa.VARCHAR(length=5), nullable=False),
        sa.Column('sub_period', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_table(
        'users',
        sa.Column('username', sa.VARCHAR(length=32), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_accepted_for_auto_payment', sa.Boolean(), nullable=True),
        sa.Column('sub_date', sa.DateTime(), nullable=True),
        sa.Column('unsub_date', sa.DateTime(), nullable=True),
        sa.Column('verified_payment_id', sa.VARCHAR(length=128), nullable=True),
        sa.Column('subscription_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DATE(), nullable=True),
        sa.Column('updated_at', sa.DATE(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_table(
        'payments',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('status', sa.VARCHAR(length=32), nullable=False),
        sa.Column('payment_amount', sa.Float(), nullable=False),
        sa.Column('payment_date', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )

    op.bulk_insert(
        subs_table,
        [
            {
                'id': 1,
                'humanize_name': 'Только потрогать',
                'payment_name': '1 месяц',
                'payment_amount': 990,
                'payment_currency': 'RUB',
                'sub_period': 1
            },
            {
                'id': 2,
                'humanize_name': 'Уверенный',
                'payment_name': '3 месяца',
                'payment_amount': 2500,
                'payment_currency': 'RUB',
                'sub_period': 3
            },
            {
                'id': 3,
                'humanize_name': 'Машина фитнеса',
                'payment_name': '1 год',
                'payment_amount': 9990,
                'payment_currency': 'RUB',
                'sub_period': 12
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('users')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
