"""Updated payment model (added payment currency)

Revision ID: 28ab792541d1
Revises: 879465ed31b5
Create Date: 2023-05-09 14:19:49.066893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ab792541d1'
down_revision = '879465ed31b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_amount', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('payment_currency', sa.VARCHAR(length=5), nullable=True))
    op.drop_column('payments', 'payment_amount_usd')
    op.drop_column('payments', 'payment_amount_rub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_amount_rub', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('payment_amount_usd', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'payment_currency')
    op.drop_column('payments', 'payment_amount')
    # ### end Alembic commands ###
