"""added sales date models

Revision ID: 2a3eeecde2a8
Revises: 69784c919e41
Create Date: 2023-07-30 08:06:26.760003

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2a3eeecde2a8'
down_revision = '6a71dd7c269c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sales_dates',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('sales_start', sa.DateTime(), nullable=True),
        sa.Column('sales_finish', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_dates')
    # ### end Alembic commands ###
