"""initial
Revision ID: 416d442196bc
Revises:
Create Date: 2023-05-08 23:58:57.100961
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "416d442196bc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("humanize_name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("payment_amount_rub", sa.Integer(), nullable=False),
        sa.Column("payment_amount_usd", sa.Integer(), nullable=False),
        sa.Column("sub_period", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id")
    )

    op.create_table(
        "users",
        sa.Column("username", sa.VARCHAR(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("sub_date", sa.DateTime(), nullable=True),
        sa.Column("unsub_date", sa.DateTime(), nullable=True),
        sa.Column("payment_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DATE(), nullable=True),
        sa.Column("updated_at", sa.DATE(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("payments")
    # ### end Alembic commands ###
