"""changed created_at and updated_at

Revision ID: 634c4d86ed63
Revises: 2a3eeecde2a8
Create Date: 2023-07-30 22:04:06.887568

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '634c4d86ed63'
down_revision = '2a3eeecde2a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column(
        'users',
        sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
