"""added is_trial marker for subscriptions

Revision ID: 6a71dd7c269c
Revises: bf9f63bc8096
Create Date: 2023-07-09 16:26:10.854385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a71dd7c269c'
down_revision = 'bf9f63bc8096'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_trial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_trial')
    # ### end Alembic commands ###
