"""Update payment model

Revision ID: 879465ed31b5
Revises: 416d442196bc
Create Date: 2023-05-09 01:16:32.947226

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '879465ed31b5'
down_revision = '416d442196bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_period_name', sa.VARCHAR(length=32), nullable=False))
    op.alter_column(
        'payments',
        'humanize_name',
        existing_type=sa.VARCHAR(length=32),
        nullable=True
    )
    op.create_unique_constraint(None, 'payments', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None,
        'users',
        type_='unique'
    )
    op.drop_constraint(
        None,
        'payments',
        type_='unique'
    )
    op.alter_column(
        'payments', 'humanize_name',
        existing_type=sa.VARCHAR(length=32),
        nullable=False
    )
    op.drop_column('payments', 'payment_period_name')
    # ### end Alembic commands ###
