"""added sub_period_type

Revision ID: bf9f63bc8096
Revises: 257717936dc6
Create Date: 2023-07-09 12:38:45.860178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9f63bc8096'
down_revision = '257717936dc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['id'])
    op.add_column('subscriptions', sa.Column('sub_period_type', sa.VARCHAR(length=32), nullable=True))
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'sub_period_type')
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
