"""added tasks for user

Revision ID: ccba70761549
Revises: 634c4d86ed63
Create Date: 2023-08-03 09:14:07.134641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccba70761549'
down_revision = '634c4d86ed63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=128), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint('task-user', 'tasks', ['id']),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task-user', 'tasks', type_='unique')
    op.drop_table('tasks')
    # ### end Alembic commands ###
